version: "2.1"
services:
    redis:
        image: "redis:latest"
        ports:
            - "6378:6379"
    mongodb:
        image: "mongo:latest"
        ports:
            - "27016:27017"
        volumes:
            - db-data:/data/db
    db:
        container_name: db
        image: mysql:5.7
        ports:
            - "13306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "mysql123"
            MYSQL_USER: "api_user"
            MYSQL_PASSWORD: "mysql123"
            MYSQL_DATABASE: "chatbot_user"
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
    service-registry:
        image: projectana/service-registry
        restart: always
        ports:
            - "80:8761"
        depends_on:
            db:
                condition: service_healthy
        healthcheck:
           test: "exit 0"
        environment:
            ANA_SERVICE_REGISTRY_PORT: 8761
    config-server:
        image: projectana/config-server
        restart: always
        ports:
            - "8888:8888"
        depends_on:
            service-registry:
                condition: service_healthy
        healthcheck:
            test: "exit 0"
        environment:
            ANA_SPRING_CLOUD_EUREKA_URL: http://service-registry:8761
            ANA_MYSQL_HOST: db
            ANA_MYSQL_PORT: 3306
            ANA_MYSQL_USERNAME: "root"
            ANA_MYSQL_PASWORD: "mysql123"
            ANA_CONFIG_SERVER_PORT: 8888
    api-gateway:
        image: projectana/api-gateway
        restart: always
        ports:
            - "8080:8080"
        depends_on:
            config-server:
                condition: service_healthy
        healthcheck:
            test: "exit 0"
        environment:
            ANA_API_GATEWAY_PORT: 8080
            ANA_CORE_URL: http://core:9500
            ANA_MESSAGES_AWS_QUEUE_ENABLED: "false"
            ANA_REDIS_CLUSTER_ENABLED: "false"
            ANA_REDIS_HOST: redis
            ANA_REDIS_PORT: 6379
            ANA_SPRING_CLOUD_EUREKA_URL: http://service-registry:8761
    ws-customers:
        image: projectana/ws-customers
        restart: always
        ports:
           - "8088:8088"
        depends_on:
            config-server:
                condition: service_healthy
        environment:
            ANA_SPRING_CLOUD_EUREKA_URL: http://service-registry:8761
            ANA_WS_CUSTOMERS_PORT: 8088
            ANA_REDIS_CLUSTER_ENABLED: "false"
            ANA_REDIS_HOST: redis
            ANA_REDIS_PORT: 6379
            ANA_MYSQL_HOST: db
            ANA_MYSQL_PORT: 3306
            ANA_MYSQL_USERNAME: "root"
            ANA_MYSQL_PASSWORD: "mysql123"
    business-service:
        image: projectana/chat.ana.businesses
        restart: always
        ports:
           - "8087:8087"
        depends_on:
            config-server:
                condition: service_healthy
        environment:
            ANA_SPRING_CLOUD_EUREKA_URL: http://service-registry:8761
            ANA_BUSINESS_SERVICE_PORT: 8087
            ANA_CORE_URL: http://core:9500
            ANA_BUSINESS_REGISTRATION_PUBLIC_ENABLED: "false"
            ANA_REDIS_HOST: redis
            ANA_REDIS_PORT: 6379
            ANA_MONGODB_URI: mongodb://mongodb:27017/anachatdb?readPreference=primary
            ANA_MYSQL_HOST: db
            ANA_MYSQL_PORT: 3306
            ANA_MYSQL_USERNAME: "root"
            ANA_MYSQL_PASSWORD: "mysql123"
    user-service:
        image: projectana/user-service
        restart: always
        ports:
           - "8089:8089"
        depends_on:
            config-server:
                condition: service_healthy
        environment:
            ANA_SPRING_CLOUD_EUREKA_URL: http://service-registry:8761
            ANA_USER_SERVICE_PORT: 8089
            ANA_REDIS_CLUSTER_ENABLED: "false"
            ANA_REDIS_HOST: redis
            ANA_REDIS_PORT: 6379
            ANA_MYSQL_HOST: db
            ANA_MYSQL_PORT: 3306
            ANA_MYSQL_USERNAME: "root"
            ANA_MYSQL_PASSWORD: "mysql123"
    core:
        image: projectana/anacore
        restart: always
        ports:
           - "9500:9500"
        depends_on:
            api-gateway:
                condition: service_healthy
        environment:
            GATEWAY_URL: http://api-gateway:8080/api
            AGENT_URL: http://ana-agent:9600/api/messages
            HOST: 0.0.0.0
            PORT: 9500
            REDIS_HOST: redis
            REDIS_PORT: 6379
            DEFAULT_BUSINESS_ID: 1213618262009721
            DB_CONNECTION: mongodb://mongodb:27017/anachatdb?readPreference=primary
            IS_AWS_ENABLED: "FALSE"

volumes:
  db-data: 
