name: auto-merge-pr
on:
  schedule:
  - cron:  "0 9 * * 1"
  workflow_dispatch:
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GH_PAT }}"
